<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $questions = [
            [
                'group_key' => 'group_clinique',
                'group_title_fr' => 'À Propos De La Clinique',
                'group_title_en' => 'About the clinic',
                'group_title_ar' => 'حول المصحة',
                'question_fr' => 'Quelles spécialités sont disponibles ?',
                'question_en' => 'Which specialties are available?',
                'question_ar' => 'ما هي التخصصات المتوفرة؟',
                'answer_fr' => "La clinique propose plusieurs spécialités médicales et chirurgicales, notamment les urgences, la chirurgie viscérale, l'urologie, la chirurgie oncologique, l'orthopédie-traumatologie, la gynécologie-obstétrique, l'anesthésie-réanimation, l'ORL, la gastro-entérologie, l'endoscopie digestive et la médecine interne.",
                'answer_en' => 'The clinic offers several medical and surgical specialties, including emergency care, visceral surgery, urology, oncologic surgery, orthopedic and trauma surgery, obstetrics and gynecology, anesthesia and intensive care, ENT, gastroenterology, digestive endoscopy and internal medicine.',
                'answer_ar' => 'تقدم المصحة عدة تخصصات طبية وجراحية، بما في ذلك الطوارئ، الجراحة الباطنية، المسالك البولية، جراحة الأورام، جراحة العظام والمفاصل، أمراض النساء والتوليد، التخدير والإنعاش، الأنف والأذن والحنجرة، أمراض الجهاز الهضمي، التنظير الهضمي والطب الباطني.',
                'order' => 3,
            ],
            [
                'group_key' => 'group_clinique',
                'group_title_fr' => 'À Propos De La Clinique',
                'group_title_en' => 'About the clinic',
                'group_title_ar' => 'حول المصحة',
                'question_fr' => 'La clinique est-elle équipée de matériel moderne ?',
                'question_en' => 'Is the clinic equipped with modern equipment?',
                'question_ar' => 'هل المصحة مجهزة بمعدات حديثة؟',
                'answer_fr' => "Oui, la clinique dispose d'un plateau technique moderne et d'équipements médicaux de pointe, permettant des diagnostics précis et une prise en charge sûre et efficace des patients.",
                'answer_en' => 'Yes, the clinic has a modern technical platform and advanced medical equipment, allowing precise diagnoses and safe, effective patient care.',
                'answer_ar' => 'نعم، تتوفر المصحة على منصة تقنية حديثة ومعدات طبية متطورة، مما يسمح بتشخيص دقيق ورعاية آمنة وفعالة للمرضى.',
                'order' => 4,
            ],
            [
                'group_key' => 'group_clinique',
                'group_title_fr' => 'À Propos De La Clinique',
                'group_title_en' => 'About the clinic',
                'group_title_ar' => 'حول المصحة',
                'question_fr' => 'La clinique accueille-t-elle tous les âges ?',
                'question_en' => 'Does the clinic welcome patients of all ages?',
                'question_ar' => 'هل تستقبل المصحة جميع الأعمار؟',
                'answer_fr' => "Oui, la clinique accueille des patients de tous âges et assure une prise en charge adaptée à chaque étape de la vie, de l'enfant à l'adulte, avec des soins personnalisés et sécurisés.",
                'answer_en' => 'Yes, the clinic welcomes patients of all ages and provides care adapted to every stage of life, from children to adults, with personalized and safe treatment.',
                'answer_ar' => 'نعم، تستقبل المصحة المرضى من جميع الأعمار وتوفر رعاية مناسبة لكل مرحلة من مراحل الحياة، من الأطفال إلى البالغين، مع علاجات شخصية وآمنة.',
                'order' => 5,
            ],
            [
                'group_key' => 'group_clinique',
                'group_title_fr' => 'À Propos De La Clinique',
                'group_title_en' => 'About the clinic',
                'group_title_ar' => 'حول المصحة',
                'question_fr' => "La clinique respecte-t-elle les normes d'hygiène ?",
                'question_en' => 'Does the clinic follow hygiene standards?',
                'question_ar' => 'هل تحترم المصحة معايير النظافة؟',
                'answer_fr' => "Oui, la clinique applique des protocoles stricts d'hygiène et de sécurité, conformes aux normes médicales en vigueur, afin de garantir des soins sûrs et un environnement sain pour tous les patients.",
                'answer_en' => 'Yes, the clinic applies strict hygiene and safety protocols in line with current medical standards to ensure safe care and a healthy environment for all patients.',
                'answer_ar' => 'نعم، تطبق المصحة بروتوكولات صارمة للنظافة والسلامة وفق المعايير الطبية المعمول بها، لضمان رعاية آمنة وبيئة صحية لجميع المرضى.',
                'order' => 6,
            ],
            [
                'group_key' => 'group_consultation',
                'group_title_fr' => 'Préparer Votre Consultation',
                'group_title_en' => 'Prepare your consultation',
                'group_title_ar' => 'التحضير للاستشارة',
                'question_fr' => 'Puis-je apporter mes anciens rapports médicaux ?',
                'question_en' => 'Can I bring my previous medical reports?',
                'question_ar' => 'هل يمكنني إحضار تقاريري الطبية السابقة؟',
                'answer_fr' => "Oui, il est fortement recommandé d'apporter vos anciens rapports médicaux, analyses et examens afin d'aider le médecin à mieux comprendre votre historique et assurer une prise en charge plus précise et adaptée.",
                'answer_en' => 'Yes, it is strongly recommended to bring your previous medical reports, tests and examinations to help the doctor better understand your history and provide more precise, adapted care.',
                'answer_ar' => 'نعم، يُنصح بشدة بإحضار تقاريرك الطبية السابقة والتحاليل والفحوصات لمساعدة الطبيب على فهم تاريخك الصحي بشكل أفضل وضمان رعاية أدق وأنسب.',
                'order' => 1,
            ],
            [
                'group_key' => 'group_consultation',
                'group_title_fr' => 'Préparer Votre Consultation',
                'group_title_en' => 'Prepare your consultation',
                'group_title_ar' => 'التحضير للاستشارة',
                'question_fr' => 'Puis-je venir accompagné(e) ?',
                'question_en' => 'Can I come accompanied?',
                'question_ar' => 'هل يمكنني الحضور مع مرافق؟',
                'answer_fr' => 'Oui, vous pouvez venir accompagné(e) lors de votre consultation. Cela est même encouragé si nécessaire pour votre confort et votre accompagnement médical.',
                'answer_en' => 'Yes, you may come accompanied during your consultation. This is even encouraged when needed for your comfort and medical support.',
                'answer_ar' => 'نعم، يمكنك الحضور مع مرافق أثناء الاستشارة. ويُشجع ذلك عند الحاجة من أجل راحتك ومواكبتك الطبية.',
                'order' => 3,
            ],
            [
                'group_key' => 'group_consultation',
                'group_title_fr' => 'Préparer Votre Consultation',
                'group_title_en' => 'Prepare your consultation',
                'group_title_ar' => 'التحضير للاستشارة',
                'question_fr' => 'Que faire en cas de retard ?',
                'question_en' => 'What should I do if I am late?',
                'question_ar' => 'ماذا أفعل في حالة التأخر؟',
                'answer_fr' => "En cas de retard, il est recommandé de prévenir la clinique dès que possible afin de réorganiser votre rendez-vous. Notre équipe fera de son mieux pour vous proposer un nouveau créneau adapté.",
                'answer_en' => 'If you are late, please inform the clinic as soon as possible so your appointment can be reorganized. Our team will do its best to offer you a suitable new time.',
                'answer_ar' => 'في حالة التأخر، يُنصح بإبلاغ المصحة في أقرب وقت ممكن لإعادة تنظيم موعدك. سيبذل فريقنا جهده لاقتراح موعد جديد مناسب.',
                'order' => 4,
            ],
            [
                'group_key' => 'group_consultation',
                'group_title_fr' => 'Préparer Votre Consultation',
                'group_title_en' => 'Prepare your consultation',
                'group_title_ar' => 'التحضير للاستشارة',
                'question_fr' => 'Puis-je annuler ou reporter mon rendez-vous ?',
                'question_en' => 'Can I cancel or reschedule my appointment?',
                'question_ar' => 'هل يمكنني إلغاء أو تأجيل موعدي؟',
                'answer_fr' => "Oui, vous pouvez annuler ou reporter votre rendez-vous en contactant la clinique par téléphone ou en vous présentant à l'accueil. Nous vous invitons à prévenir à l'avance afin de mieux organiser les consultations.",
                'answer_en' => 'Yes, you can cancel or reschedule your appointment by contacting the clinic by phone or at reception. Please notify us in advance so consultations can be better organized.',
                'answer_ar' => 'نعم، يمكنك إلغاء أو تأجيل موعدك عبر الاتصال بالمصحة هاتفياً أو الحضور إلى الاستقبال. نرجو إبلاغنا مسبقاً لتنظيم الاستشارات بشكل أفضل.',
                'order' => 5,
            ],
            [
                'group_key' => 'group_consultation',
                'group_title_fr' => 'Préparer Votre Consultation',
                'group_title_en' => 'Prepare your consultation',
                'group_title_ar' => 'التحضير للاستشارة',
                'question_fr' => 'Dois-je préparer des informations avant la consultation ?',
                'question_en' => 'Should I prepare information before the consultation?',
                'question_ar' => 'هل يجب أن أحضر معلومات قبل الاستشارة؟',
                'answer_fr' => "Oui, il est conseillé de préparer vos antécédents médicaux, traitements en cours et anciens examens afin de faciliter le diagnostic et assurer une prise en charge plus précise et adaptée.",
                'answer_en' => 'Yes, it is recommended to prepare your medical history, current treatments and previous examinations to help diagnosis and ensure more precise, adapted care.',
                'answer_ar' => 'نعم، يُنصح بتحضير تاريخك الطبي والعلاجات الحالية والفحوصات السابقة لتسهيل التشخيص وضمان رعاية أدق وأنسب.',
                'order' => 6,
            ],
            [
                'group_key' => 'group_services',
                'group_title_fr' => 'Services & Soins',
                'group_title_en' => 'Services & care',
                'group_title_ar' => 'الخدمات والرعاية',
                'question_fr' => 'Proposez-vous des soins à domicile ?',
                'question_en' => 'Do you provide home care?',
                'question_ar' => 'هل تقدمون الرعاية المنزلية؟',
                'answer_fr' => 'Actuellement, la clinique ne propose pas de soins à domicile, mais assure une prise en charge complète et adaptée au sein de ses services.',
                'answer_en' => 'Currently, the clinic does not provide home care, but offers comprehensive and adapted care within its departments.',
                'answer_ar' => 'حالياً، لا تقدم المصحة رعاية منزلية، لكنها توفر رعاية شاملة ومناسبة داخل مصالحها.',
                'order' => 0,
            ],
            [
                'group_key' => 'group_services',
                'group_title_fr' => 'Services & Soins',
                'group_title_en' => 'Services & care',
                'group_title_ar' => 'الخدمات والرعاية',
                'question_fr' => 'La clinique réalise-t-elle des interventions chirurgicales ?',
                'question_en' => 'Does the clinic perform surgical procedures?',
                'question_ar' => 'هل تقوم المصحة بإجراء تدخلات جراحية؟',
                'answer_fr' => "Oui, la clinique réalise différentes interventions chirurgicales grâce à une équipe de chirurgiens spécialisés et des équipements modernes, assurant une prise en charge sûre et efficace des patients.",
                'answer_en' => 'Yes, the clinic performs various surgical procedures thanks to a team of specialist surgeons and modern equipment, ensuring safe and effective patient care.',
                'answer_ar' => 'نعم، تقوم المصحة بإجراء تدخلات جراحية مختلفة بفضل فريق من الجراحين المتخصصين ومعدات حديثة، مما يضمن رعاية آمنة وفعالة للمرضى.',
                'order' => 1,
            ],
            [
                'group_key' => 'group_services',
                'group_title_fr' => 'Services & Soins',
                'group_title_en' => 'Services & care',
                'group_title_ar' => 'الخدمات والرعاية',
                'question_fr' => 'Quels types de traitements proposez-vous ?',
                'question_en' => 'What types of treatments do you offer?',
                'question_ar' => 'ما أنواع العلاجات التي تقدمونها؟',
                'answer_fr' => 'La clinique propose des traitements médicaux et chirurgicaux adaptés à chaque patient, incluant la prise en charge des pathologies aiguës et chroniques, avec un suivi personnalisé assuré par des spécialistes.',
                'answer_en' => 'The clinic offers medical and surgical treatments adapted to each patient, including care for acute and chronic conditions, with personalized follow-up by specialists.',
                'answer_ar' => 'تقدم المصحة علاجات طبية وجراحية مناسبة لكل مريض، بما في ذلك رعاية الأمراض الحادة والمزمنة، مع متابعة شخصية من طرف متخصصين.',
                'order' => 2,
            ],
            [
                'group_key' => 'group_services',
                'group_title_fr' => 'Services & Soins',
                'group_title_en' => 'Services & care',
                'group_title_ar' => 'الخدمات والرعاية',
                'question_fr' => 'Quels protocoles de traitement sont proposés aux patients ?',
                'question_en' => 'What treatment protocols are offered to patients?',
                'question_ar' => 'ما بروتوكولات العلاج المقترحة للمرضى؟',
                'answer_fr' => 'La clinique propose des protocoles de traitement adaptés à chaque patient, basés sur un diagnostic précis et une prise en charge personnalisée, allant des traitements médicaux aux interventions chirurgicales selon les besoins.',
                'answer_en' => 'The clinic offers treatment protocols adapted to each patient, based on precise diagnosis and personalized care, ranging from medical treatment to surgical procedures depending on needs.',
                'answer_ar' => 'تقدم المصحة بروتوكولات علاج مناسبة لكل مريض، مبنية على تشخيص دقيق ورعاية شخصية، من العلاجات الطبية إلى التدخلات الجراحية حسب الحاجة.',
                'order' => 3,
            ],
            [
                'group_key' => 'group_services',
                'group_title_fr' => 'Services & Soins',
                'group_title_en' => 'Services & care',
                'group_title_ar' => 'الخدمات والرعاية',
                'question_fr' => 'Comment se fait le diagnostic des patients ?',
                'question_en' => 'How are patients diagnosed?',
                'question_ar' => 'كيف يتم تشخيص المرضى؟',
                'answer_fr' => "Le diagnostic des patients est réalisé à travers une consultation médicale, un examen clinique et, si nécessaire, des examens complémentaires (analyses, imagerie médicale) afin d'assurer une évaluation précise et une prise en charge adaptée.",
                'answer_en' => 'Patients are diagnosed through a medical consultation, clinical examination and, when necessary, complementary tests such as lab work or medical imaging to ensure precise evaluation and adapted care.',
                'answer_ar' => 'يتم تشخيص المرضى من خلال استشارة طبية وفحص سريري، وعند الحاجة فحوصات إضافية مثل التحاليل أو التصوير الطبي لضمان تقييم دقيق ورعاية مناسبة.',
                'order' => 4,
            ],
        ];

        foreach ($questions as $question) {
            DB::table('cms_faq')->updateOrInsert(
                [
                    'group_key' => $question['group_key'],
                    'question_fr' => $question['question_fr'],
                ],
                array_merge($question, [
                    'active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ])
            );
        }
    }

    public function down(): void
    {
        $questions = [
            'Quelles spécialités sont disponibles ?',
            'La clinique est-elle équipée de matériel moderne ?',
            'La clinique accueille-t-elle tous les âges ?',
            "La clinique respecte-t-elle les normes d'hygiène ?",
            'Puis-je apporter mes anciens rapports médicaux ?',
            'Puis-je venir accompagné(e) ?',
            'Que faire en cas de retard ?',
            'Puis-je annuler ou reporter mon rendez-vous ?',
            'Dois-je préparer des informations avant la consultation ?',
            'Proposez-vous des soins à domicile ?',
            'La clinique réalise-t-elle des interventions chirurgicales ?',
            'Quels types de traitements proposez-vous ?',
            'Quels protocoles de traitement sont proposés aux patients ?',
            'Comment se fait le diagnostic des patients ?',
        ];

        DB::table('cms_faq')->whereIn('question_fr', $questions)->delete();
    }
};
